# Generated by Django 6.0.1 on 2026-02-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=5)),
                ('division', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('E2', 'E2'), ('F1', 'F1'), ('F2', 'F2'), ('G1', 'G1'), ('G2', 'G2'), ('H1', 'H1'), ('H2', 'H2'), ('I1', 'I1'), ('I2', 'I2'), ('J1', 'J1'), ('J2', 'J2'), ('K1', 'K1'), ('K2', 'K2'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('name', models.CharField(blank=True, editable=False, max_length=100)),
                ('total_seats', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ['standard', 'division'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Under_Review', 'Documents Verified'), ('Approved', 'Offer Letter Sent'), ('Admitted', 'Fee Paid & Enrolled'), ('Rejected', 'Rejected'), ('Waitlist', 'Waitlisted')], default='Pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admission_docs/photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='admission_docs/id_proofs/')),
                ('previous_mark_sheet', models.FileField(blank=True, null=True, upload_to='admission_docs/marks/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='admission_docs/tc/')),
                ('admitted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to=settings.AUTH_USER_MODEL)),
                ('first_language', models.ForeignKey(limit_choices_to={'subject_type': 'Language'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_first_lang', to='school_system.subject')),
                ('optional_subject', models.ForeignKey(limit_choices_to={'subject_type': 'Elective'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_optional', to='school_system.subject')),
                ('second_language', models.ForeignKey(limit_choices_to={'subject_type': 'Language'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_second_lang', to='school_system.subject')),
                ('stream_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_system.stream')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='admission_docs/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admission.admissionapplication')),
            ],
        ),
    ]
