"""
Django settings for school_system project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^xq5b2uii**+7=mp8dj0t-8-!t5(7!%iw#+0dfo@z6#^4bovj+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  

# --- CSRF & SECURITY FIX FOR LOCALHOST ---
# Explicitly allowing localhost and 127.0.0.1 to prevent Origin/CSRF rejections
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] 

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
# -----------------------------------------

# Application definition
INSTALLED_APPS = [
    # 1. Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # 2. Your Master App Config (This wakes up your signals)
    'school_system.apps.SchoolSystemConfig',
    
    # 3. Your Eduplex Modules
    'admission',
    'library',
    'fees',
    'attendance',
    'student_info',
    'staff',
    'transportation',
    'workload',
    'form_builder',
    'lms',
    'exam',
    'timetable',
    'captcha',
    'dashboard',
    'communication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- INTERNATIONALIZATION & TIMEZONE ---
LANGUAGE_CODE = 'en-us'

# UPDATED: Set to local Kerala time (Indian Standard Time)
TIME_ZONE = 'Asia/Kolkata' 

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]


# --- URL REDIRECTS ---
LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# --- SESSION SECURITY (WORKDAY OPTIMIZED) ---
# 1. Clear session when the browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 2. UPDATED: 36000 seconds = 10 Hours (Workday Length)
SESSION_COOKIE_AGE = 36000 

# 3. Reset the timer on every new page load
SESSION_SAVE_EVERY_REQUEST = True

# 4. Security Lockdown: Prevent JS access to session cookie
SESSION_COOKIE_HTTPONLY = True


# --- CAPTCHA CONFIGURATION ---
CAPTCHA_FONT_SIZE = 32
CAPTCHA_LENGTH = 5
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#000000'


# --- MEDIA FILES ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'