# Generated by Django 6.0.1 on 2026-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Faculty Member'), ('Admin', 'Root Administrator'), ('Cashier', 'Financial Officer'), ('Librarian', 'Library Admin'), ('Office_Staff', 'Front Desk Operations'), ('Dept_Admin', 'Department Head')], default='Teacher', max_length=20),
        ),
    ]
