# Generated by Django 6.0.1 on 2026-02-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('school_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique Institutional ID (e.g., STU2026001)', max_length=20, unique=True)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pursuing', 'Pursuing'), ('passed_out', 'Passed Out'), ('discontinued', 'Discontinued'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], db_index=True, default='pursuing', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to disable login access for this student.')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('primary_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='Passport Size Photo', null=True, upload_to='student_photos/')),
                ('id_proof', models.FileField(blank=True, help_text='Aadhar/Passport/ID Card', null=True, upload_to='student_docs/id_proofs/')),
                ('previous_mark_sheet', models.FileField(blank=True, null=True, upload_to='student_docs/mark_sheets/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='student_docs/tc/')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admission.classroom')),
                ('first_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_first_lang', to='school_system.subject')),
                ('optional_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_optional', to='school_system.subject')),
                ('second_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_second_lang', to='school_system.subject')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_system.stream')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['student_id'],
            },
        ),
    ]
