# Generated by Django 6.0.1 on 2026-02-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Root Administrator'), ('Teacher', 'Faculty Member'), ('Student', 'Student'), ('Cashier', 'Financial Officer'), ('Librarian', 'Library Admin'), ('Office_Staff', 'Front Desk Ops'), ('Dept_Admin', 'Department Head')], default='Student', max_length=15),
        ),
    ]
