# Generated by Django 6.0.1 on 2026-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('none', 'None (Simulation Mode)'), ('twilio', 'Twilio API'), ('meta', 'Meta WhatsApp Cloud API')], default='none', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='Twilio Auth Token OR Meta Bearer Token', max_length=255, null=True)),
                ('account_sid', models.CharField(blank=True, help_text='Twilio Account SID (Leave blank if using Meta)', max_length=255, null=True)),
                ('sender_number', models.CharField(blank=True, help_text='Your Twilio outgoing number (e.g., +123456789) or Meta Phone Number ID', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Communication API Settings',
                'verbose_name_plural': 'Communication API Settings',
            },
        ),
    ]
