"""
Django settings for school_system project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import dj_database_url
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^xq5b2uii**+7=mp8dj0t-8-!t5(7!%iw#+0dfo@z6#^4bovj+'

# Turns off Debug mode on Render, keeps it True locally
DEBUG = 'RENDER' not in os.environ

# --- CSRF & SECURITY FIX ---
ALLOWED_HOSTS = ['localhost', '127.0.0.1'] 
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://nsbhss-sms.onrender.com',
    'https://*.onrender.com', # Wildcard for Render subdomains
]

# Automatically allow the Render deployment URL
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Security Headers for Render Proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = False 

# Secure Cookie Settings — only enforce HTTPS cookies on Render (production)
_ON_RENDER = 'RENDER' in os.environ
CSRF_COOKIE_SECURE = _ON_RENDER
SESSION_COOKIE_SECURE = _ON_RENDER
# NOTE: CSRF_COOKIE_HTTPONLY must remain False (default) so JS can read the cookie
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Application definition
INSTALLED_APPS = [
    # 1. Django Core Apps
    'unfold',  # [ADDED FOR PREMIUM ADMIN] Must be before admin
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', 
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # 2. Your Master App Config
    'school_system.apps.SchoolSystemConfig',
    
    # 3. Your Eduplex Modules
    'admission',
    'library',
    'fees',
    'attendance',
    'student_info',
    'staff',
    'transportation',
    'workload',
    'form_builder',
    'lms',
    'exam',
    'timetable',
    'captcha',
    'dashboard',
    'communication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_system.wsgi.application'


# [UPDATED FOR RENDER DATABASE]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Override default DB if DATABASE_URL is provided
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# --- INTERNATIONALIZATION & TIMEZONE ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata' 
USE_I18N = True
USE_TZ = True


# --- STATIC FILES CONFIGURATION ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

# [ADDED FOR RENDER/WHITENOISE]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True  
WHITENOISE_MANIFEST_STRICT = False  


# --- HIGH-END ADMIN COMMAND CENTER (UNFOLD) ---
UNFOLD = {
    "SITE_TITLE": "NSHSS Mannar Admin",
    "SITE_HEADER": "Eduplex Dashboard",
    "SITE_URL": "/",
    "SITE_SYMBOL": "school",
    "DASHBOARD_CALLBACK": "school_system.dashboard.get_dashboard_stats",
    "COLORS": {
        "primary": {
            "50": "240 253 244", "100": "220 252 231", "200": "187 247 208",
            "300": "134 239 172", "400": "74 222 128", "500": "34 197 94",
            "600": "22 163 74", "700": "21 128 61", "800": "15 56 34",
            "900": "20 83 45", "950": "5 46 22",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Academic Control",
                "separator": True,
                "items": [
                    {"title": "Students", "link": "/admin/student_info/student/", "icon": "person_search"},
                    {"title": "Attendance", "link": "/admin/attendance/attendancelog/", "icon": "event_available"},
                    {"title": "Exams", "link": "/admin/exam/exam/", "icon": "assignment"},
                    {"title": "Timetables", "link": "/admin/timetable/timetableentry/", "icon": "calendar_month"},
                    {"title": "Classrooms", "link": "/admin/admission/classroom/", "icon": "meeting_room"},
                ],
            },
            {
                "title": "Operational Hub",
                "separator": True,
                "items": [
                    {"title": "Admissions", "link": "/admin/admission/admissionapplication/", "icon": "app_registration"},
                    {"title": "Fees & Payments", "link": "/admin/fees/payment/", "icon": "payments"},
                    {"title": "Library Books", "link": "/admin/library/book/", "icon": "local_library"},
                    {"title": "Transport Stories", "link": "/admin/transportation/route/", "icon": "directions_bus"},
                ],
            },
            {
                "title": "People & Org",
                "separator": True,
                "items": [
                    {"title": "Staff Directory", "link": "/admin/staff/staff/", "icon": "badge"},
                    {"title": "Messages", "link": "/admin/communication/broadcastmessage/", "icon": "chat"},
                    {"title": "Form Builder", "link": "/admin/form_builder/customform/", "icon": "dynamic_form"},
                ],
            },
            {
                "title": "Core System",
                "items": [
                    {"title": "Users", "link": "/admin/auth/user/", "icon": "manage_accounts"},
                    {"title": "Streams", "link": "/admin/school_system/stream/", "icon": "lan"},
                    {"title": "Subjects", "link": "/admin/school_system/subject/", "icon": "menu_book"},
                ],
            },
        ],
    },
    "STYLES": [
        lambda request: static("css/admin_custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/admin_run_btn.js"),
    ],
    "GLOBAL_SEARCH": [
        {
            "title": "Students",
            "model": "student_info.Student",
            "placeholder": "Search by ID or Name...",
        },
        {
            "title": "Staff Members",
            "model": "staff.Staff",
            "placeholder": "Search directory...",
        },
    ],
}


# --- URL REDIRECTS ---
LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# --- SESSION SECURITY (WORKDAY OPTIMIZED) ---
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 36000 
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE is set at the top for production safety


# --- CAPTCHA CONFIGURATION ---
CAPTCHA_FONT_SIZE = 32
CAPTCHA_LENGTH = 5
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#000000'


# --- MEDIA FILES ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- EMAIL CONFIGURATION (PASSWORD RESET) ---
# Defaults to Console backend for testing. Override via ENV for production.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Sender address for system emails
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'NSHSS Mannar <noreply@nshss.edu.in>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL