# Generated by Django 6.0.1 on 2026-02-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_system', '0001_initial'),
        ('student_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MID', 'Mid-Term'), ('FINAL', 'Final Exam'), ('TEST', 'Monthly Test')], default='MID', max_length=10)),
                ('academic_session', models.CharField(default='2025-2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('weightage', models.IntegerField(default=100, help_text='Percentage weight in final result')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=5)),
                ('min_percentage', models.IntegerField()),
                ('max_percentage', models.IntegerField()),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, help_text="Teacher's specific comment", max_length=200)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_info.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.subject')),
            ],
            options={
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
