# Generated by Django 6.0.1 on 2026-02-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
        ('attendance', '0001_initial'),
        ('school_system', '0001_initial'),
        ('staff', '0001_initial'),
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(fields=('classroom', 'subject', 'date'), name='unique_attendance_log'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('log', 'student'), name='unique_student_attendance_record'),
        ),
    ]
