# Generated by Django 6.0.1 on 2026-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_communicationsettings_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsettings',
            name='provider',
            field=models.CharField(choices=[('none', 'None (Simulation Mode)'), ('local', 'Custom Local Node API (Free)'), ('ultramsg', 'Ultramsg (Free API)'), ('twilio', 'Twilio API'), ('meta', 'Meta Cloud API')], default='none', max_length=20),
        ),
    ]
