# Generated by Django 6.0.1 on 2026-02-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('school_system', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, help_text='The teacher in charge of this specific class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_system.stream'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='class_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_lang1', to='school_system.subject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='optional_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_optional', to='school_system.subject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='second_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_lang2', to='school_system.subject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_system.stream'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('standard', 'division')},
        ),
    ]
