# Generated by Django 6.0.1 on 2026-02-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('select', 'Dropdown'), ('checkbox', 'Checkbox')], max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated options')),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_builder.customform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('custom_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form_builder.customform')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
