# Generated by Django 6.0.1 on 2026-02-25 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='category',
            field=models.CharField(default='General', help_text='e.g., Admissions, Leave, Feedback', max_length=100),
        ),
        migrations.AddField(
            model_name='customform',
            name='limit_responses',
            field=models.PositiveIntegerField(default=0, help_text='Set to 0 for unlimited'),
        ),
        migrations.AddField(
            model_name='customform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Staff Only)'), ('published', 'Published (Active)'), ('archived', 'Archived (Historical)')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='customform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma-separated options (for Dropdown/Checkbox)'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHOW', 'Show'), ('HIDE', 'Hide')], default='SHOW', max_length=10)),
                ('operator', models.CharField(choices=[('equals', 'Is Equal To'), ('not_equals', 'Is Not Equal To')], default='equals', max_length=20)),
                ('value', models.CharField(help_text='The answer value that triggers this rule', max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_rules', to='form_builder.customform')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_by', to='form_builder.formfield')),
                ('trigger_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='form_builder.formfield')),
            ],
        ),
    ]
